language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw
  - psql -c 'DROP DATABASE IF EXISTS studioadmintoolkit;' -U postgres
  - psql -c 'CREATE DATABASE studioadmintoolkit;' -U postgres
  - psql -U postgres -d studioadmintoolkit -a -f src/main/resources/schema.sql
